:- module(cfg_ai, [hate/2, role/2, mania/2]).

hate(orc, elf).
hate(orc, dwarf).
hate(orc, human).
hate(elf, orc).
hate(elf, goblin).
hate(elf, undead).
hate(dwarf, orc).
hate(dwarf, goblin).
hate(dwarf, demon).
hate(human, undead).
hate(human, demon).
hate(paladin, undead).
hate(paladin, demon).
hate(paladin, vampire).
hate(paladin, cultist).
hate(paladin, necromancer).
hate(cleric, undead).
hate(cleric, vampire).
hate(undead, paladin).
hate(undead, cleric).
hate(undead, human).
hate(demon, angel).
hate(demon, paladin).
hate(angel, demon).
hate(angel, undead).
hate(angel, vampire).
hate(vampire, werewolf).
hate(vampire, paladin).
hate(vampire, cleric).
hate(werewolf, vampire).
hate(werewolf, guard).
hate(guard, thief).
hate(guard, bandit).
hate(guard, cultist).
hate(guard, murderer).
hate(guard, werewolf).
hate(guard, monster).
hate(thief, guard).
hate(bandit, guard).
hate(bandit, merchant).
hate(bandit, noble).
hate(cultist, guard).
hate(cultist, paladin).
hate(necromancer, paladin).

role(guard, protector).
role(paladin, protector).
role(citizen, worker).
role(peasant, worker).
role(miner, worker).
role(merchant, trader).
role(scholar, wanderer).
role(priest, healer).
role(cleric, healer).

mania(vampire, sanguivore).
mania(bat, sanguivore).
mania(leech, sanguivore).
mania(giant_spider, sanguivore).
mania(cultist, pyromaniac).
mania(fire_sprite, pyromaniac).
mania(salamander, pyromaniac).
mania(imp, pyromaniac).
mania(thief, kleptomaniac).
mania(monkey, kleptomaniac).
mania(bandit, mugger).
mania(goblin, hoarder).
mania(rat, hoarder).
mania(dragon, hoarder).
mania(raven, hoarder).
mania(zealot, martyr).
mania(elemental, martyr).
mania(assassin, murderer).
mania(dark_knight, murderer).
mania(wraith, murderer).
mania(ghoul, cannibal).
mania(zombie, cannibal).
mania(orc, cannibal).
mania(demon, sadist).
mania(dark_elf, sadist).
mania(interrogator, sadist).
